server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/osap_open_source?parseTime=True&loc=Local
  redis:
    addr: 192.168.50.109:16379
    password: "Shds@402"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt_key: hqFr%3ddt32DGlSTOI5cO6@TH#fFwYnP$S
email:
  enable: false
  from: "osap.work@qq.com"
  smtp_host: "smtp.qq.com"
  smtp_port: 587
  smtp_username: "osap.work@qq.com"
  smtp_password: "dkcgahsacpdcbdjg"
collect:
  enable: true
  token: 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
