server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/osap_user?parseTime=True&loc=Local
  redis:
    addr: 192.168.50.109:16379
    password: "Shds@402"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

email:
  from: "osap.work@qq.com"
  smtp_host: "smtp.qq.com"
  smtp_port: 587
  smtp_username: "osap.work@qq.com"
  smtp_password: "dkcgahsacpdcbdjg"

auth:
  jwt_key: hqFr%3ddt32DGlSTOI5cO6@TH#fFwYnP$S