// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: api/open_source/v1/open_source.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenSource_GetLanguage_FullMethodName       = "/open_source.v1.OpenSource/GetLanguage"
	OpenSource_GetOwner_FullMethodName          = "/open_source.v1.OpenSource/GetOwner"
	OpenSource_GetRepo_FullMethodName           = "/open_source.v1.OpenSource/GetRepo"
	OpenSource_GetRepoCategory_FullMethodName   = "/open_source.v1.OpenSource/GetRepoCategory"
	OpenSource_GetRepoByCategory_FullMethodName = "/open_source.v1.OpenSource/GetRepoByCategory"
)

// OpenSourceClient is the client API for OpenSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenSourceClient interface {
	GetLanguage(ctx context.Context, in *LanguageRequest, opts ...grpc.CallOption) (*LanguageReply, error)
	GetOwner(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*OwnerReply, error)
	GetRepo(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoReply, error)
	GetRepoCategory(ctx context.Context, in *RepoCategoryRequest, opts ...grpc.CallOption) (*RepoCategoryReply, error)
	GetRepoByCategory(ctx context.Context, in *RepoByCategoryRequest, opts ...grpc.CallOption) (*RepoByCategoryReply, error)
}

type openSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenSourceClient(cc grpc.ClientConnInterface) OpenSourceClient {
	return &openSourceClient{cc}
}

func (c *openSourceClient) GetLanguage(ctx context.Context, in *LanguageRequest, opts ...grpc.CallOption) (*LanguageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LanguageReply)
	err := c.cc.Invoke(ctx, OpenSource_GetLanguage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openSourceClient) GetOwner(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*OwnerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OwnerReply)
	err := c.cc.Invoke(ctx, OpenSource_GetOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openSourceClient) GetRepo(ctx context.Context, in *RepoRequest, opts ...grpc.CallOption) (*RepoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoReply)
	err := c.cc.Invoke(ctx, OpenSource_GetRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openSourceClient) GetRepoCategory(ctx context.Context, in *RepoCategoryRequest, opts ...grpc.CallOption) (*RepoCategoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoCategoryReply)
	err := c.cc.Invoke(ctx, OpenSource_GetRepoCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openSourceClient) GetRepoByCategory(ctx context.Context, in *RepoByCategoryRequest, opts ...grpc.CallOption) (*RepoByCategoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoByCategoryReply)
	err := c.cc.Invoke(ctx, OpenSource_GetRepoByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenSourceServer is the server API for OpenSource service.
// All implementations must embed UnimplementedOpenSourceServer
// for forward compatibility.
type OpenSourceServer interface {
	GetLanguage(context.Context, *LanguageRequest) (*LanguageReply, error)
	GetOwner(context.Context, *OwnerRequest) (*OwnerReply, error)
	GetRepo(context.Context, *RepoRequest) (*RepoReply, error)
	GetRepoCategory(context.Context, *RepoCategoryRequest) (*RepoCategoryReply, error)
	GetRepoByCategory(context.Context, *RepoByCategoryRequest) (*RepoByCategoryReply, error)
	mustEmbedUnimplementedOpenSourceServer()
}

// UnimplementedOpenSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenSourceServer struct{}

func (UnimplementedOpenSourceServer) GetLanguage(context.Context, *LanguageRequest) (*LanguageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLanguage not implemented")
}
func (UnimplementedOpenSourceServer) GetOwner(context.Context, *OwnerRequest) (*OwnerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOwner not implemented")
}
func (UnimplementedOpenSourceServer) GetRepo(context.Context, *RepoRequest) (*RepoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepo not implemented")
}
func (UnimplementedOpenSourceServer) GetRepoCategory(context.Context, *RepoCategoryRequest) (*RepoCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepoCategory not implemented")
}
func (UnimplementedOpenSourceServer) GetRepoByCategory(context.Context, *RepoByCategoryRequest) (*RepoByCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepoByCategory not implemented")
}
func (UnimplementedOpenSourceServer) mustEmbedUnimplementedOpenSourceServer() {}
func (UnimplementedOpenSourceServer) testEmbeddedByValue()                    {}

// UnsafeOpenSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenSourceServer will
// result in compilation errors.
type UnsafeOpenSourceServer interface {
	mustEmbedUnimplementedOpenSourceServer()
}

func RegisterOpenSourceServer(s grpc.ServiceRegistrar, srv OpenSourceServer) {
	// If the following call pancis, it indicates UnimplementedOpenSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenSource_ServiceDesc, srv)
}

func _OpenSource_GetLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenSourceServer).GetLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenSource_GetLanguage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenSourceServer).GetLanguage(ctx, req.(*LanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenSource_GetOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenSourceServer).GetOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenSource_GetOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenSourceServer).GetOwner(ctx, req.(*OwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenSource_GetRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenSourceServer).GetRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenSource_GetRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenSourceServer).GetRepo(ctx, req.(*RepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenSource_GetRepoCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenSourceServer).GetRepoCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenSource_GetRepoCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenSourceServer).GetRepoCategory(ctx, req.(*RepoCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenSource_GetRepoByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenSourceServer).GetRepoByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenSource_GetRepoByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenSourceServer).GetRepoByCategory(ctx, req.(*RepoByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenSource_ServiceDesc is the grpc.ServiceDesc for OpenSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "open_source.v1.OpenSource",
	HandlerType: (*OpenSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLanguage",
			Handler:    _OpenSource_GetLanguage_Handler,
		},
		{
			MethodName: "GetOwner",
			Handler:    _OpenSource_GetOwner_Handler,
		},
		{
			MethodName: "GetRepo",
			Handler:    _OpenSource_GetRepo_Handler,
		},
		{
			MethodName: "GetRepoCategory",
			Handler:    _OpenSource_GetRepoCategory_Handler,
		},
		{
			MethodName: "GetRepoByCategory",
			Handler:    _OpenSource_GetRepoByCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/open_source/v1/open_source.proto",
}
